### ISSUE TITLE
When I choose different ratio then brewing method select disappears

### ISSUE THREAD

**Issue by mispulino** [hitovo/hitovo#1]
- Choose some brewing method
- Change the ratio

Actual: Select of the brewing method disappears
Expected: Select should remain

Additional: Also the select get back when you change the ratio to the default.

Chrome v80, MacOS Catalina

**Comment by vanekj** [comment]
Hi @mispulino, could you please attach GIF of the bad behaviour? I am not able to reflect the described issue. Thank you!

**Comment by mispulino** [comment]
![select_hitovo](https://user-images.githubusercontent.com/48277325/78259098-7fa01680-74fc-11ea-9046-f020fce9be98.gif)
There you go @vanekj

**Comment by vanekj** [comment]
Hi @mispulino, changes are live, thank you!
